### PR TITLE
Avatar editor ui revamp

### PR DESCRIPTION
**Pull request by jordanmlacalle**
Candidate PR to update Avatar Editor UI per issue #40 .

This PR reworks the Avatar Editor UI to align it more with the rest of the app. It also adds a custom RoundedButton that can be used to reduce code duplication. This button could be dropped into profile.dart and EditProfile.dart to reduce the duplicated code of those buttons while providing a consistent UX/UI.

### CODE REVIEW

**Review by Cryptonex7 — CHANGES_REQUESTED** [review]
Hey @jordanmlacalle We are glad that you contributted to this project.

- the UI looks significantly better than what we had before! Very good implementation.
- However, the functionality seems to be a bit broken as after doing the changes, when we save the new Avatar - the avatar goes blank.
- Also, please use Icons.arrow_left instead of the outlined variant as it is causing some version conflicts. and similarly the same with the right arrow too.

**Comment by Cryptonex7** [comment]
Also, @jordanmlacalle, extremely sorry for the delay in our response - we had so many PRs to review in more of our associated Open sourced projects of KIDE. 

We are sorry for the inconvenience caused, we are trying our best to do justice to each and every contribution.
Thanks for your patience.

**Comment by jordanmlacalle** [comment]
@Cryptonex7 Thank you for the feedback! I'll revisit this later today and make changes accordingly.

**Comment by vanshBhatia-A4k9** [comment]
Firstly, @jordanmlacalle , Thanks a lot for contributing to this project! We've tested your PR and it's almost ready to be merged, we had a few minor suggestions that we'd be grateful if you could change. I've added the screenshots and a brief description of the changes requested below for visualization purposes: 

- Please consider improving the spacing between the avatar property to customize and the options:

WhatsApp Image 2020-10-11 at 5 31 06 PM

- Some padding can be put on the tab highlighting or the AvatarEditorContainer itself:

WhatsApp Image 2020-10-11 at 5 31 20 PM

- There's unused space on top of the Avatar whereas the Avatar, the button, and the AvatarEditorContainer are stacked very close to each other, evenly spreading the above can lead to better utilization of the space:

WhatsApp Image 2020-10-11 at 5 32 27 PM

Once again, thanks for contributing to this project, hoping to hear back from you soon!

**Review by vanshBhatia-A4k9 — CHANGES_REQUESTED** [review]
Check above comments for a detailed description of the requested changes

**Comment by Cryptonex7** [comment]
@jordanmlacalle, 

- Considering @A4k9 's inputs, I think putting the value text between the arrows, (like: **<** _Medium Hair_ **>** ) would help a bit.
- Also maybe consider reducing the font sizes.
- For the space left at the top, you might want to consider shifting the save button to the right (trailing edge) of the app bar (just an idea, you can avoid it if this seems to be difficult).
- Also, everything can be pushed a tad bit up on the screen to consider smaller screen sizes.

Thanks, we will be awaiting your changes with a lot of excitement. 
Please note - if this goes well you will receive a certificate from the team KIDE, acknowledging your contribution - as this particular issue is a **significant** change to our project!

**Comment by jordanmlacalle** [comment]
@Cryptonex7 , @A4k9
 
Thanks for the details! I'm starting to look back at this now and throughout the day. I'll do my best with the spacing between the avatar and editor, but unfortunately the extra spacing above the avatar is actually part of the SVG image. I think moving the save button the the AppBar as you suggested should alleviate some of the crowding.

**Comment by Cryptonex7** [comment]
Sure @jordanmlacalle, if that is the case, please do whatever best is possible in terms of optimizing the space.

**Comment by jordanmlacalle** [comment]
@Cryptonex7 Pushed some changes. 

- Added a ScrollBar to the editor body so the user has visual indication of when scrolling has ended
- Moved the "Save" button to the AppBar. Kept the same styling. Let me know if it should be restyled
- Fixed the issue where the Avatar was not being saved properly anymore
- Decreased font size of avatar property title and value in the editor
- Moved property value text in between the arrows. Enabled overflow wrapping on this text.
- Added some padding to the editor container

Some screenshots below:

Screenshot_20201012-162312
Screenshot_20201012-162352

One thought for another issue is that the Avatar does not update throughout the app after saving. Fixing this might require keeping some global state of the avatar properties and updating this on press of the "Save" button as well. Could be a usecase for some state management like Provider + ChangeNotifier, etc. But best logged as a separate issue.

Let me know any other feedback you have or design / feature you might want in the editor! 

Thanks

**Comment by Cryptonex7** [comment]
Hey @jordanmlacalle - thanks for the fixes. We will soon review this. Sorry for the delay. We are a team based in India - so there will be a 12 hour time lag between our communications :) 

We will keep you posted about these changes - and soon send you the review.

Rest assured - the entire team is very excited about this particular PR.

Thanks

**Comment by Cryptonex7** [comment]
Hey @jordanmlacalle, things look good here - can you just make the save button a bit smaller, and maybe reduce the padding in the button?

**Review by vanshBhatia-A4k9 — CHANGES_REQUESTED** [review]
Hey @jordanmlacalle, just looked at the new designs, amazing work 💯. If possible, please look into the padding of the Avatar edit options container, I noticed that it's not centered (Comparing the padding from left and right on the container, it can be seen in the Screenshots you provided as well), except that everything looks great here. This is well on it's way to become one of the most helpful PRs we've gotten thus far. A special thanks to you from our team regardless of the HacktoberFest!

**Comment by jordanmlacalle** [comment]
@Cryptonex7 , @A4k9 
Made some minor adjustments, here's a new screenshot:

image

Sorry for the time between these changes!

**Review by vanshBhatia-A4k9 — APPROVED** [review]
Tested, LGTM..
Thanks again for all your efforts @jordanmlacalle.

**Comment by vanshBhatia-A4k9** [comment]
@Cryptonex7 Please review.

**Comment by vanshBhatia-A4k9** [comment]
@jordanmlacalle, we will soon be giving you a certificate acknowledging all your work towards our project, please accept it as a sign of gratitude from team KIDE for choosing to invest your precious time into helping us with this issue. 👍  🥇

**Review by Cryptonex7 — APPROVED** [review]
Works as reported by @A4k9.

Congratulations @jordanmlacalle and thank you for your PR - you will be receiving the certificate shortly.

**Comment by Cryptonex7** [comment]
# Congratulations @jordanmlacalle 

Your PR has really been of significant importance for team KIDE. Therefore, We would like to acknowledge you efforts through this certificate.

Feel free to upload this on LinkedIn or any social media - and if you do that, also link our repository with it so that we could get more such awesome contributions from people like you.

We are also looking forward to have you contribute more to KIDE. Please consider recontributing to more of our listed issues.

Thanks and Regards,
Team Kide.

Jordan Moreno-Lacalle

**Pull request merged**
