### PR TITLE
Fixed #38: Bottom padding in contact page

### LINKED ISSUE #38: [BUG]:contacts page bottom padding
## **Describe the bug**
content in contacts page gets overlapped by bottom nav bar

## **Screenshots**

Screenshot_1601667088

### PR DESCRIPTION
**Pull request by ibrahimbroachwala**
Added SliverPadding inside CustomScrollView with bottom padding as 64.

### CODE REVIEW

**Comment by Cryptonex7** [comment]
@A4k9 Can you please review this one?

**Comment by Cryptonex7** [comment]
@sambitraze Please review this as this is your issue and neither me nor @A4k9 are able to reproduce this issue.

**Review by sambitraze — APPROVED** [review]
nice, changes can be merged

**Review by Cryptonex7 — APPROVED** [review]
Works as reported by @sambitraze.

Ready to Merge! Labeling as Hacktoberfest-accepted.

**Comment by Cryptonex7** [comment]
## Congratulations @ibrahimbroachwala ,
We are honoured to have you contributing to Kide.

We would like you to do more such contributions!

Please accept this token of acknowledgement from us and feel free to upload this to your LinkedIn profile or other portfolios.

Ibrahim Broachwala

**Comment by ibrahimbroachwala** [comment]
Thanks 🤗

**Pull request merged**
