### PR TITLE
Settings in drawer modified- closes #24

### LINKED ISSUE #24: "Help and feedback" & "Privacy Policy" Buttons inside settings not working.
## Description
- The Help & Feedback feature is there on the side drawer - which is functional. However, the same button in the settings Page is not working. 
- And the Privacy policy button is totally non-functional.

## Potential Solution
- Copy the action that happens on pressing the Help and Feedback Button from the side drawer to the one in the settings page. 
- Remove the Privacy Policy Button (We dont have it ready yet - we will add it once we are done with the policy).

## Supporting Images
Screenshot_20201002-141200

### PR DESCRIPTION
**Pull request by Ayushi673**

### CODE REVIEW

**Review by Cryptonex7 — COMMENTED** [review]
The changes in the code look good! They follow good practices. So green flag for that.

We will move on to checking the functionality of the changes.

Stay Tuned @Ayushi673 .

**Comment by Cryptonex7** [comment]
@sambitraze Can you please review this PR?

**Comment by sambitraze** [comment]
ok sure

**Review by sambitraze — APPROVED** [review]

**Review by sambitraze — APPROVED** [review]

**Review by theRealKIDE — APPROVED** [review]
Works as reported by @sambitraze  - ready for merge.

**Review by Cryptonex7 — APPROVED** [review]
Congratulations @Ayushi673  - you will recieve your certificate soon!

Labeling as Hacktoberfest-accepted!

**Comment by Ayushi673** [comment]
Thanks a lot @Cryptonex7 ! Looking forward to working more on this repository.

**Comment by Cryptonex7** [comment]
## Congratulations @Ayushi673,
We are honoured to have you contributing to Kide.

We would like you to do more such contributions!

Please accept this token of acknowledgement from us and feel free to upload this to your LinkedIn profile or other portfolios.

Ayushi Das

**Comment by Cryptonex7** [comment]
Ready to merge - Merging to Master.

Thanks again @Ayushi673

**Pull request merged**
